//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPR.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPR.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application already installed.
        /// </summary>
        public static string ApplicationAlreadyInstalled {
            get {
                return ResourceManager.GetString("ApplicationAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application {0} has already been installed. Do you want to delete the existing application and install this package?.
        /// </summary>
        public static string ApplicationAlreadyInstalledDescription {
            get {
                return ResourceManager.GetString("ApplicationAlreadyInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The installation has been canceled!.
        /// </summary>
        public static string ApplicationInstallError_Canceled {
            get {
                return ResourceManager.GetString("ApplicationInstallError_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application package contains invalid manifest files!.
        /// </summary>
        public static string ApplicationInstallError_InvalidManifestFiles {
            get {
                return ResourceManager.GetString("ApplicationInstallError_InvalidManifestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application package is missing manifest files!.
        /// </summary>
        public static string ApplicationInstallError_MissingManifestFiles {
            get {
                return ResourceManager.GetString("ApplicationInstallError_MissingManifestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application has been successfully installed!.
        /// </summary>
        public static string ApplicationInstallError_None {
            get {
                return ResourceManager.GetString("ApplicationInstallError_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application package is not in decrypted format!.
        /// </summary>
        public static string ApplicationInstallError_NotDecrypted {
            get {
                return ResourceManager.GetString("ApplicationInstallError_NotDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application type is currently not yet supported!.
        /// </summary>
        public static string ApplicationInstallError_NotSupportedAppType {
            get {
                return ResourceManager.GetString("ApplicationInstallError_NotSupportedAppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unexpected error occured during the installation.&amp;#13;&amp;#13;Please check the log for more info..
        /// </summary>
        public static string ApplicationInstallError_UnexpectedError {
            get {
                return ResourceManager.GetString("ApplicationInstallError_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error executing application.
        /// </summary>
        public static string AppRunError {
            get {
                return ResourceManager.GetString("AppRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse.
        /// </summary>
        public static string BrowsePath {
            get {
                return ResourceManager.GetString("BrowsePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data storage.
        /// </summary>
        public static string DataStoragePath {
            get {
                return ResourceManager.GetString("DataStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your GamerTag....
        /// </summary>
        public static string EnterYourGamerTag {
            get {
                return ResourceManager.GetString("EnterYourGamerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application encountered an unexpected error while executing. Please check the log for more detailed info!.
        /// </summary>
        public static string ExceptionRunApp {
            get {
                return ResourceManager.GetString("ExceptionRunApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation failed.
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation succeed.
        /// </summary>
        public static string InstallationSucceed {
            get {
                return ResourceManager.GetString("InstallationSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing application....
        /// </summary>
        public static string InstallingApp {
            get {
                return ResourceManager.GetString("InstallingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install new application.
        /// </summary>
        public static string InstallNewAppToolTip {
            get {
                return ResourceManager.GetString("InstallNewAppToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launching in process....
        /// </summary>
        public static string LaunchingInProcess {
            get {
                return ResourceManager.GetString("LaunchingInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result default data storage path.
        /// </summary>
        public static string RestoreDefaultStorage {
            get {
                return ResourceManager.GetString("RestoreDefaultStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for applications....
        /// </summary>
        public static string SearchForAppSearchBar {
            get {
                return ResourceManager.GetString("SearchForAppSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully changed.
        /// </summary>
        public static string SuccessfullyChanged {
            get {
                return ResourceManager.GetString("SuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data directory will be used for the next launch of the runner!.
        /// </summary>
        public static string SuccessfullyChangedDataPathMsg {
            get {
                return ResourceManager.GetString("SuccessfullyChangedDataPathMsg", resourceCulture);
            }
        }
    }
}
